### ISSUE TITLE
data compare plot code

### ISSUE THREAD

**Issue by AllofLife** [LarryDong/FusionTracking#2]
[3] Event feature tracking evaluation codes: https://github.com/uzh-rpg/rpg_feature_tracking_analysis This amazing tool can draw beautiful curves. The following pictures show the "feature age" and "tracking error" of 4 different method: ours, ICP method, EKLT, and EM-ICP. Please check the paper for more details.

can you show me the way and the data to use this code to plot compare?

**Comment by LarryDong** [comment]
Hi,

I think you should first see this tool's repo for help. Please check [this](https://github.com/uzh-rpg/rpg_feature_tracking_analysis#preparing-the-data).  
Then you can just save result of this `FusionTracking` method into the same format as introduced in evaluation tool.

If you have any trouble using evaluation tool, please pull an issue on that repo; if you have trouble to prepare data from this `FusionTracking`  repo, feel free to reply on this issue. I believe that tool is easy to use.

**Comment by AllofLife** [comment]
Can you share the code related to saving data, my programming skills are very poor, I believe many people are looking forward to this code！
thank you！

**Comment by LarryDong** [comment]
Hi,

这代码我短时间改不了了，系统环境配置起来太麻烦了。但你可以这样试下：

1. 创建一个c++的文件writer，最简单的方式是初始化一个全局的writer，用iostream或直接cout到文件都可以，每次特征位置更新后进行保存；
2. 特征的所有历史位置都存在`center_history`当中（在[这一行](https://github.com/LarryDong/FusionTracking/blob/main/fusion_tracker/include/patch.h#L89)），所以在[每次更新后](https://github.com/LarryDong/FusionTracking/blob/eeddc59ce8c21c057e57d78ed3d96f1a4b7fba34/fusion_tracker/src/fusion_tracker.cpp#L173)，你都保存一下最新的特征位置就好；
3. 额外注意：RPG的这个代码feature_tracking_analysis有两个问题：a) 不能中途添加特征，只能跟踪所有的初始特征，所以在保存时，你需要在[特征初始化完成时](https://github.com/LarryDong/FusionTracking/blob/eeddc59ce8c21c057e57d78ed3d96f1a4b7fba34/fusion_tracker/src/fusion_tracker.cpp#L273)先保存一次。b) 同时不能跟踪特征时长过短的特征，可能会报错，不知道现在这个问题官方解决了么，如果跟踪时初始化的特征时长过短，可能需要手动删除输出的特征对应行。
4. 如果你不用RPG的tool，不用在意第3条，直接在[每个特征丢失时](https://github.com/LarryDong/FusionTracking/blob/eeddc59ce8c21c057e57d78ed3d96f1a4b7fba34/fusion_tracker/src/fusion_tracker.cpp#L178)，把所有`center_history`保存到文件就好，按照你后面需要处理的数据格式。

只能帮你这么多了，真的没时间给你把这个代码改出来。

**Comment by LarryDong** [comment]
The saving codes are simple, just adding some c++ file writer after every feature's update ([this line](https://github.com/LarryDong/FusionTracking/blob/main/fusion_tracker/include/patch.h#L89)).

Due to my computer environment is different now, I won't add the codes recently.


Some hints:  
For RPG's feature_tracking_analysis tool, all the features should be initalized and cannot add new features, so make sure to write all initialized features into the output file after initialization ([this line](https://github.com/LarryDong/FusionTracking/blob/eeddc59ce8c21c057e57d78ed3d96f1a4b7fba34/fusion_tracker/src/fusion_tracker.cpp#L273)).  Also, the tool may failed when the feature age is too short, so maybe some features should be deleted manually if this issue still happens today.

Good luck.
